### PR TITLE
Adapt CDZ client function to download data, not upload it

### PR DESCRIPTION
**Pull request by tobischo**
CDZ was faultily implemented as an upload in the client.rb.

It was correctly implemented in the specific CDZ class though.

This corrects the inconsistency

Addresses #90

### CODE REVIEW

**Review by bumi — APPROVED** [review]

**Comment by tobischo** [comment]
@bumi Do you happen to have some experience with JRuby and OpenSSL?
I am having a hard time getting the tests to work.

I am also wondering whether we need to keep supporting JRuby - for us it would be no problem to remove it.

**Comment by bumi** [comment]
Sadly no. The last time I used it was many, many years ago. :)
I don't know how important jruby is these days.

**Comment by tobischo** [comment]
Considering that it does not seem to be working and considering that no one from railslove appears to be really maintaining epics in that regard, I would argue that it can be removed. Anyone who wants to move to a newer epics version and requires jruby would then be able to contribute that piece of functionality again.

**Comment by bumi** [comment]
+1 from my side. 

As you say if somebody wants to use the new epics with jruby they can contribute.

**Pull request merged**
