### PR TITLE
add FDL order type

### PR DESCRIPTION
**Pull request by frantisekrokusek**
FDL is the standard download file order in EBICS 2.5

### CODE REVIEW

**Comment by frantisekrokusek** [comment]
@tobischo Here is the PR for the FDL order type.
Thanks for your review 🙏

**Comment by tobischo** [comment]
Thank you for splitting it up.
Do you happen to have some documentation on the FDL order type that I can refer to when checking this?

**Comment by tobischo** [comment]
https://www.ibm.com/docs/en/b2b-integrator/6.1.1?topic=types-fdl-order-type

Found this as a description of the FDL order type

**Comment by frantisekrokusek** [comment]
You can find the specifications in the [2.5 final specifications chapter 9.6](https://www.ebics.org/en/technical-information/archive-ebics/specification) Diagram 103 
You have the definition in the XSD files in your specs or [here under H004 specs](https://www.ebics.org/en/technical-information/archive-ebics/schema)
[EBICS_Specification_2.5_final-16-05-2011.pdf](https://github.com/user-attachments/files/18177451/EBICS_Specification_2.5_final-16-05-2011.pdf)
image

**Comment by tobischo** [comment]
Thanks 😄 
That helps and got me to the question I was pondering about when just looking at the code.

Shouldn't we include from/to as optional values to be passed, since a date range can be provided?

**Comment by frantisekrokusek** [comment]
Indeed I will add those optional fields!

**Comment by frantisekrokusek** [comment]
@tobischo it's ready 🙏 Have nice last day of the year!

**Pull request merged**
