### PR TITLE
enables unzipping of special zipfiles

### PR DESCRIPTION
**Pull request by Uepsilon**
- before zipfiles with general purpose bit flag 3 set could not have
  been read, see rubyzip doc regarding bit 3 (0x08)

Source: https://github.com/rubyzip/rubyzip#notice-about-zipinputstream

### CODE REVIEW

**Comment by bumi** [comment]
can I have a poster with "ness code is better code" ? :)

**Comment by bumi** [comment]
ups

**Comment by Uepsilon** [comment]
> no idea about the zip stuff, but looks good to me!

i derived that from "no code is best code"..

**Comment by bumi** [comment]
no code is better than no code. 

should still get posters with that. would be cool actually. maybe we should ask iza

**Pull request merged**
