### PR TITLE
Adapt to BREAKING change in faraday v0.16.2

### PR DESCRIPTION
**Pull request by leoarnold**
The faraday gem has decided to differentiate between request body
and response body, thereby dropping the use of the `:body` key in `env`

https://github.com/lostisland/faraday/commit/6e3c40f159ef514064d05faabf6c6f261662970b

This is in perfect alignment with semantic versioning as breaking
changes in minor increments are legal before v1.0.0.

As faraday `>= 0.16.0` is only available for Ruby `>= 2.3`
the change broke only the builds for newer Ruby versions.

### CODE REVIEW

**Comment by leoarnold** [comment]
The `faraday` team has reverted the problematic change **for now**:

> The v0.16.0 -> v0.16.2 releases will be removed from Rubygems and all changes contained in master will be released as v1.0.
> https://github.com/lostisland/faraday/releases/tag/v0.17.0

**Comment by bumi** [comment]
:+1: thanks for the update. 
So we need to adopt your changes for 1.0? are those actually backwards compatible?

**Comment by leoarnold** [comment]
@bumi This PR has been tested against faraday `v0.(15|16|17).x`.

The change suggested here is merely "use getter and setter instead of relying on the Hash-like `self.[]`"

**Comment by Uepsilon** [comment]
looks very good. thank you for your contribution.

**Pull request merged**
